version: '3'
services:
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=db
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=db
    ports:
      - '5432:5432'
    expose:
      - '5432'
volumes:
  pgadmindata:
